config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do

  constraints(SubdomainPresent) do
    root to: 'dashboard#index', as: :dashboard_root
    devise_for :users
  end

  constraints(SubdomainBlank) do
    root to: 'home#index'

    # Account creation
    resources :accounts, only: [:new, :create]
  end
  
end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :owner, class_name: 'User'

  validates :owner, presence: true

  validates :subdomain, presence: true,
                        uniqueness: true,
                        subdomain: true

  validates :company_name, presence: true,
                           uniqueness: true

  accepts_nested_attributes_for :owner
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:new, :create]

  def new
    @account = Account.new
    @account.build_owner
  end

  def create
    @account = Account.new(account_params)
    if @account.valid?
      Apartment::Tenant.create(@account.subdomain)
      Apartment::Tenant.switch(@account.subdomain)
      @account.save
      redirect_to new_user_session_url(subdomain: @account.subdomain)
    else
      render action: 'new'
    end
  end

  private

  def account_params
    params.require(:account).permit(:company_name, :subdomain, owner_attributes: [:email, :password, :password_confirmation])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :load_schema, :authenticate_user!

  def current_tenant
    Apartment::Tenant.current_tenant
  end
  helper_method :current_tenant

  private

  def load_schema
    Apartment::Tenant.switch('public')
    return unless request.subdomain.present?

    account = Account.find_by(subdomain: request.subdomain)
    if account
      Apartment::Tenant.switch(request.subdomain)
    else
      redirect_to root_url(subdomain: false)
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!, only: :index

  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/accounts/new.html.erb
<h1>Create an account</h1>

<%= simple_form_for(@account) do |f| %>
  <%= f.simple_fields_for :owner do |p| %>
    <%= p.label :email %>
    <%= p.input_field :email %>

    <%= p.label :password %>
    <%= p.input_field :password %>

    <%= p.label :password_confirmation %>
    <%= p.input_field :password_confirmation %>
  <% end %>

  <%= f.label :company_name %>
  <%= f.input_field :company_name %>

  <%= f.label :subdomain %>
  <%= f.input_field :subdomain %>

  <%= f.button :submit, value: 'Create Account' %>
<% end %>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Rails 4 Multi Tenancy</h1>
  <p>This is an example of a full-featured multi tenancy app with Rails 4</p>
  <p>
    <%= link_to 'Create Your Account', new_account_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>
    
<h2><%= current_tenant %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Securitytrends</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav class="navbar navbar-static-top navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Security Trends', root_path(subdomain: nil), class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Sign out', destroy_user_session_path(subdomain: nil), method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Look Up Our Plans', '#' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

<div class="container">

  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %> 

  <div class="row">
    <%= yield %>
  </div>
</div>

</body>
</html>